#!/bin/sh -e

gtk-update-icon-cache -f /usr/share/icons/hicolor

oldversion="$2"
if [ -z "$oldversion" ]; then
	maemo-select-menu-location portabase.desktop
fi

if [ -x /usr/bin/update-mime-database ]; then
	update-mime-database /usr/share/mime
fi
if [ -x /usr/bin/update-desktop-database ]; then
	update-desktop-database /usr/share/applications
fi
if [ -x /usr/bin/hildon-update-category-database ]; then
	hildon-update-category-database /usr/share/mime
fi

exit 0
