.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PORTABASE 1 "June 6, 2020"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
portabase \- an easy\-to\-use personal database application
.SH SYNOPSIS
.B portabase
[ \-h | \-\-help | \fI<file>\fP ]
.br
.B portabase
command [ \-p password ] [ options ] \fI<fromfile>\fP \fI<tofile>\fP
.SH DESCRIPTION
\fIPortaBase\fP (portable database) is a personal database application
that is available for many platforms, including Linux, Mac OS X, Windows,
and Maemo.
.PP
PortaBase's features include:
.PP
\- One data table per file
.PP
\- String, Integer, Decimal, Boolean, Note (multi\-line text), Date,
  Time, Calculation, Sequence, Image, and Enum column types
.PP
\- Add, edit, and delete rows of data
.PP
\- Custom data views (subsets of the columns in any order)
.PP
\- Filter the displayed rows using sets of conditions
.PP
\- Sort the rows by any combination of columns, each in ascending or
  descending order
.PP
\- Optional page navigation buttons, with a custom number of rows per page
.PP
\- Add, delete, rearrange, and rename columns at any time
.PP
\- Specify default values for columns
.PP
\- View summary statistics for columns (total, average, min, max, etc.)
.PP
\- Import data from CSV, XML, and MobileDB files
.PP
\- Export data to CSV, HTML, and XML files
.PP
\- Command\-line format conversions (to and from XML, from MobileDB, to HTML)
.PP
\- Print the data grid with view, sorting, and filter applied
.PP
\- Fullscreen mode option
.PP
\- Optional data file encryption
.PP
\- Unicode support
.PP
\- Pick any available font to use throughout the application
.SH COMMANDS
\fIPortaBase\fP uses the following commands to indicate a command-line
file conversion:
.TP
\fBfromxml\fP
Create a new PortaBase file from the input XML file.
.TP
\fBfrommobiledb\fP
Create a new PortaBase file from the input MobileDB file.
.TP
\fBfromcsv\fP
Add rows to an existing PortaBase file from the input CSV file.
.TP
\fBtoxml\fP
Create a new XML file from the input PortaBase file.
.TP
\fBtocsv\fP
Create a new CSV file from the input PortaBase file.
.TP
\fBtohtml\fP
Create a new HTML file from the input PortaBase file.
.PP
If an encrypted PortaBase file is to be read or created, the following
option can be used immediately after the command:
.TP
\fB\-p\fP \fI<password>\fP
Open or create the encrypted PortaBase file using the given password
.PP
The toxml, tocsv, and tohtml commands accept the following options:
.TP
\fB\-v\fP \fI<view>\fP
Apply the named view before exporting.
.TP
\fB\-s\fP \fI<sorting>\fP
Apply the named sorting before exporting.
.TP
\fB\-f\fP \fI<filter>\fP
Apply the named filter before exporting.
.PP
Options which can be used for both fromcsv and tocsv:
.TP
\fB\-\-headers\fP
The CSV file does or should contain an initial row of column headers.
.TP
\fB\-d\fP \fI<delimiter>\fP
The character to be used as a field delimiter.  Defaults to a comma,
use the string "tab" to indicate a tab character.
.TP
\fB\-e\fP \fI<encoding>\fP
Specifies the text encoding of the file; typical options are UTF\-8
(the default), Latin\-1, UTF\-16, Shift\-JIS, etc.
.PP
The fromcsv command supports one additional option:
.TP
\fB\-\-add\-unknown\-enum\-options\fP
Automatically add unknown enum options rather than treating them as
invalid data.
The fromcsv command also supports one additional option:
.TP
\fB\-l\fP \fI<line ending>\fP
Indicates how each line in the CSV file is to be ended.  By default
UNIX/Mac\-style newline characters are used, but specifying "crlf"
indicates that a Windows\-style carriage return and newline should
be used instead.
.SH OPTIONS
\fIPortaBase\fP accepts the following options:
.TP
.TP
\fB\-h\fP, \fB\-\-help\fP
Display usage instructions.
.SH FILES
\fB$HOME\fP/.qt/portabaserc \- user\-specific settings.  Stores
information on font, checkbox editing, delete confirmations, etc.
.SH AUTHOR
This manual page was written by Jeremy Bowman <jmbowman@alum.mit.edu>,
for the Debian GNU/Linux system (but may be used by others).
