.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PORTABASE 1 "March 12, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
portabase \- an easy\-to\-use personal database application
.SH SYNOPSIS
.B portabase
[ \-h | \-\-help | \-f \fI<file>\fP ]
.br
.B portabase
command [ \-p password ] [ options ] \fI<fromfile>\fP \fI<tofile>\fP
.SH DESCRIPTION
\fIPortaBase\fP (portable database) is a personal database application
originally written for the Linux\-based models of Sharp Zaurus PDA (and
should work on any other Linux PDA using the Qtopia environment.)  It
can now also be run as a Linux or Windows desktop application.
.PP
PortaBase's features include:
.PP
\- One data table per file
.PP
\- String, Integer, Decimal, Boolean, Note (multi\-line text), Date,
  Time, and Enum column types
.PP
\- Add, edit, and delete rows of data
.PP
\- Custom data views (subsets of the columns in any order)
.PP
\- Filter the displayed rows using sets of conditions
.PP
\- Sort the rows by any combination of columns, each in ascending or
  descending order
.PP
\- Page navigation buttons, with a custom number of rows per page
.PP
\- Add, delete, rearrange, and rename columns at any time
.PP
\- Specify default values for columns
.PP
\- View summary statistics for columns (total, average, min, max, etc.)
.PP
\- Import data from CSV, XML, and MobileDB files
.PP
\- Export data to CSV and XML files
.PP
\- Command\-line format conversions (to and from XML, from MobileDB)
.PP
\- Data file encryption
.PP
\- Unicode support
.PP
\- Pick any available font to use throughout the application
.SH COMMANDS
\fIPortaBase\fP uses the following commands to indicate a command-line
file conversion:
.TP
\fBfromxml\fP
Create a new PortaBase file from the input XML file.
.TP
\fBfrommobiledb\fP
Create a new PortaBase file from the input MobileDB file.
.TP
\fBfromcsv\fP
Add rows to an existing PortaBase file from the input CSV file.
.TP
\fBtoxml\fP
Create a new XML file from the input PortaBase file.
.TP
\fBtocsv\fP
Create a new CSV file from the input PortaBase file.
.PP
If an encrypted PortaBase file is to be read or created, the following
option can be used immediately after the command:
.TP
\fB\-p\fP \fI<password>\fP
Open or create the encrypted PortaBase file using the given password
.PP
The toxml and tocsv commands accept the following options:
.TP
\fB\-v\fP \fI<view>\fP
Apply the named view before exporting.
.TP
\fB\-s\fP \fI<sorting>\fP
Apply the named sorting before exporting.
.TP
\fB\-f\fP \fI<filter>\fP
Apply the named filter before exporting.
.PP
The fromcsv command supports one option:
.TP
\fB\-e\fP \fI<encoding>\fP
Specifies the text encoding of the imported CSV file; options are UTF-8
(the default) and Latin-1.
.SH OPTIONS
\fIPortaBase\fP accepts the following options:
.TP
\fB\-f\fP \fI<file>\fP
Open the specified file.
.TP
\fB\-h\fP, \fB\-\-help\fP
Display usage instructions.
.SH FILES
/etc/portabase.conf \- general configuration settings for all users.
Contains the paths where application icons and the help file are found.
.PP
\fB$HOME\fP/.portabase/portabase.conf \- user\-specific settings.  Stores
information on font, checkbox editing, delete confirmations, etc.
.PP
\fB$HOME\fP/.portabase/qpe.conf \- user\-specific settings which on the
Zaurus are part of the system settings shared by all applications.
Stores date format, week start day, etc.
.SH AUTHOR
This manual page was written by Jeremy Bowman <jmbowman@alum.mit.edu>,
for the Debian GNU/Linux system (but may be used by others).
